version: '3.8'
services:
  minireal:
    container_name: minireal
    image: pazed/minireal:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8090:8090
    volumes:
      - ./data:/usr/src/app/data
#      - ./minireal_data:/usr/src/app/minireal_data

